### ISSUE TITLE
cabal update 挂起

### ISSUE THREAD

**Issue by boboyada** [winterland1989/magic-haskell#11]
1、我安装ubuntu 16.10 kylin,haskell-platform 8.01 for 通用版

2、按照你的文档
cabal install --only-dependencies
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: code-0.1.0.0 (user goal)
next goal: MonadRandom (dependency of code-0.1.0.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

3、运行cabal update 挂起，没有反映。

检查版本
4、ghci --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
5、cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
6、stack --version
Version 1.1.2 x86_64 hpack-0.14.0
7、which ghci
/usr/local/bin/ghci
8、which cabal
/usr/local/bin/cabal

不知道问题出在哪？

9、我之前就安装haskell-platform for ubuntu ,是7的版本，同样现象

**Comment by winterland1989** [comment]
估计是你的网络环境问题，`cabal update`会下载最新的package meta，建议你按照[这里](https://mirrors.tuna.tsinghua.edu.cn/help/hackage/)的教程配置tuna镜象来加速。

**Comment by boboyada** [comment]
谢谢winterland1989.
 cabal update
Downloading the latest package lists from:
- mirrors.tuna.tsinghua.edu.cn
- hackage.haskell.org
故障依旧
可能是版本，没有看到remote repo,现贴出部分内容
cd .cabal
boboant@boboant-ThinkPad-W530:~/.cabal$ ls
config  packages
boboant@boboant-ThinkPad-W530:~/.cabal$ more config
-- This is the configuration file for the 'cabal' command line tool.

-- The available configuration options are listed below.
-- Some of them have default values listed.

-- Lines (like this one) beginning with '--' are comments.
-- Be careful with spaces and indentation because they are
-- used to indicate layout for nested sections.

-- Cabal library version: 1.24.0.0
-- cabal-install version: 1.24.0.0

remote-repo: mirrors.tuna.tsinghua.edu.cn:http://mirrors.tuna.tsinghua.edu.cn/ha
ckage
-- remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive

repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- secure: False
  -- root-keys:
  -- key-threshold:

-- default-user-config:
-- require-sandbox: False
-- ignore-sandbox: False
-- ignore-expiry: False
-- http-transport:
remote-repo-cache: /home/boboant/.cabal/packages
-- local-repo:
-- logs-dir:
world-file: /home/boboant/.cabal/world
-- verbose: 1
-- compiler: ghc
-- with-compiler:
-- with-hc-pkg:
-- program-prefix: 
-- program-suffix: 
-- library-vanilla: True
-- library-profiling:
-- shared:
-- executable-dynamic: False
-- profiling:
-- executable-profiling:
-- profiling-detail:
-- library-profiling-detail:
下面省了

**Comment by winterland1989** [comment]
你把你的cabal配置文件（~/.cabal/config）内容发出来吧，新版的cabal的格式稍有不同，需要你删除和remote相关的几行之后在添加镜像源。你先试着把这几行删了：

```
repository hackage.haskell.org
url: http://hackage.haskell.org/
-- secure: False
-- root-keys:
-- key-threshold:
```

**Comment by boboyada** [comment]
1、改下面这样后，出现：
cabal update
Downloading the latest package list from hackage.haskell.org
Skipping download: local and remote files match.
2、config的完整内容

-- This is the configuration file for the 'cabal' command line tool.

-- The available configuration options are listed below.
-- Some of them have default values listed.

-- Lines (like this one) beginning with '--' are comments.
-- Be careful with spaces and indentation because they are
-- used to indicate layout for nested sections.

-- Cabal library version: 1.24.0.0
-- cabal-install version: 1.24.0.0

-- remote-repo: mirrors.tuna.tsinghua.edu.cn:http://mirrors.tuna.tsinghua.edu.cn/hackage
-- remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive

repository hackage.haskell.org
  url:http://mirrors.tuna.tsinghua.edu.cn/hackage
  -- secure: False
  -- root-keys:
  -- key-threshold:

-- default-user-config:
-- require-sandbox: False
-- ignore-sandbox: False
-- ignore-expiry: False
-- http-transport:
remote-repo-cache: /home/boboant/.cabal/packages
-- local-repo:
-- logs-dir:
world-file: /home/boboant/.cabal/world
-- verbose: 1
-- compiler: ghc
-- with-compiler:
-- with-hc-pkg:
-- program-prefix: 
-- program-suffix: 
-- library-vanilla: True
-- library-profiling:
-- shared:
-- executable-dynamic: False
-- profiling:
-- executable-profiling:
-- profiling-detail:
-- library-profiling-detail:
-- optimization: True
-- debug-info: False
-- library-for-ghci:
-- split-objs: False
-- executable-stripping: True
-- library-stripping: True
-- configure-option:
-- user-install: True
-- package-db:
-- flags:
-- extra-include-dirs:
-- extra-lib-dirs:
-- extra-framework-dirs:
extra-prog-path: /home/boboant/.cabal/bin
-- tests: False
-- coverage: False
-- library-coverage:
-- allow-newer: False
-- exact-configuration: False
-- benchmarks: False
-- relocatable: False
-- cabal-lib-version:
-- constraint:
-- preference:
-- solver: choose
-- documentation: False
-- doc-index-file: $datadir/doc/$arch-$os-$compiler/index.html
-- max-backjumps: 2000
-- reorder-goals: False
-- shadow-installed-packages: False
-- strong-flags: False
-- reinstall: False
-- avoid-reinstalls: False
-- force-reinstalls: False
-- upgrade-dependencies: False
-- root-cmd:
-- symlink-bindir:
build-summary: /home/boboant/.cabal/logs/build.log
-- build-log:
remote-build-reporting: anonymous
-- report-planning-failure: False
-- one-shot: False
-- run-tests:
jobs: $ncpus
-- offline: False
-- username:
-- password:
-- password-command:
-- builddir:

haddock
  -- keep-temp-files: False
  -- hoogle: False
  -- html: False
  -- html-location:
  -- for-hackage: False
  -- executables: False
  -- tests: False
  -- benchmarks: False
  -- all:
  -- internal: False
  -- css:
  -- hyperlink-source: False
  -- hscolour-css:
  -- contents-location:

install-dirs user
  -- prefix: /home/boboant/.cabal
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $abi/$libname
  -- libexecdir: $prefix/libexec
  -- datadir: $prefix/share
  -- datasubdir: $abi/$pkgid
  -- docdir: $datadir/doc/$abi/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir
  -- sysconfdir: $prefix/etc

install-dirs global
  -- prefix: /usr/local
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $abi/$libname
  -- libexecdir: $prefix/libexec
  -- datadir: $prefix/share
  -- datasubdir: $abi/$pkgid
  -- docdir: $datadir/doc/$abi/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir
  -- sysconfdir: $prefix/etc

program-locations
  -- alex-location:
  -- ar-location:
  -- c2hs-location:
  -- cpphs-location:
  -- gcc-location:
  -- ghc-location:
  -- ghc-pkg-location:
  -- ghcjs-location:
  -- ghcjs-pkg-location:
  -- greencard-location:
  -- haddock-location:
  -- happy-location:
  -- haskell-suite-location:
  -- haskell-suite-pkg-location:
  -- hmake-location:
  -- hpc-location:
  -- hsc2hs-location:
  -- hscolour-location:
  -- jhc-location:
  -- ld-location:
  -- lhc-location:
  -- lhc-pkg-location:
  -- pkg-config-location:
  -- strip-location:
  -- tar-location:
  -- uhc-location:

program-default-options
  -- alex-options:
  -- ar-options:
  -- c2hs-options:
  -- cpphs-options:
  -- gcc-options:
  -- ghc-options:
  -- ghc-pkg-options:
  -- ghcjs-options:
  -- ghcjs-pkg-options:
  -- greencard-options:
  -- haddock-options:
  -- happy-options:
  -- haskell-suite-options:
  -- haskell-suite-pkg-options:
  -- hmake-options:
  -- hpc-options:
  -- hsc2hs-options:
  -- hscolour-options:
  -- jhc-options:
  -- ld-options:
  -- lhc-options:
  -- lhc-pkg-options:
  -- pkg-config-options:
  -- strip-options:
  -- tar-options:
  -- uhc-options:

**Comment by boboyada** [comment]
貌似通过  cabal update，
但cabal install --only-dependencies时，出现问题。
建议在haskell-platform 8.01 for 通用版（手动下载安装）的环境下测试一下

cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: primitive (dependency of conduit-extra-1.1.15)
rejecting: primitive-0.6.1.0/installed-Ip4... (conflict: primitive =>
transformers==0.5.2.0/installed-0.5..., code => transformers>=0.4 && <0.5)
trying: primitive-0.6.2.0
trying: scientific-0.3.4.6/installed-9fC... (dependency of
attoparsec-0.13.1.0)
next goal: vector (dependency of scientific-0.3.4.6/installed-9fC...)
rejecting: vector-0.11.0.0/installed-6uB... (conflict: primitive==0.6.2.0,
vector => primitive==0.6.1.0/installed-Ip4...)
rejecting: vector-0.11.0.0, vector-0.10.12.3, vector-0.10.12.2,
vector-0.10.12.1, vector-0.10.11.0, vector-0.10.10.0, vector-0.10.9.2,
vector-0.10.9.1, vector-0.10.9.0, vector-0.10.0.1, vector-0.10, vector-0.9.1,
vector-0.9, vector-0.8, vector-0.7.1, vector-0.7.0.1, vector-0.7,
vector-0.6.0.2, vector-0.6.0.1, vector-0.6, vector-0.5, vector-0.4.2,
vector-0.4.1, vector-0.4, vector-0.3.1, vector-0.3, vector-0.2, vector-0.1,
vector-0.10.12.0, vector-0.10.9.3 (conflict: scientific =>
vector==0.11.0.0/installed-6uB...)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

**Comment by winterland1989** [comment]
这个问题属于cabal的问题了，建议私聊哈，我邮箱drkoster@qq.com，你把你的工程的cabal文件也发过来吧。

**Comment by boboyada** [comment]
git clone https://github.com/winterland1989/magic-haskell.git
cd ./magic-haskell/code
就是这个项目呀。
