### ISSUE TITLE
cabal install --only-dependencies  fail!!!

### ISSUE THREAD

**Issue by boboyada** [winterland1989/magic-haskell#12]
根据书的README的描述，在解决第一个cabal update问题后，对本书源代码进行如下操作，出现问题。建议：对于本书的源码，在不同的haskell-platform环境（7.x和8.x两个版本）下，分别测试一下。以帮助阅读本书的读者更好的消化内容。
我的环境是
kylin ubuntu linux 16.10,先是通过sudo apt install haskell-platform,安装后，ghci --version发现是7.10的版本，不是8.01，同时在cabal update时，挂起，于是sudo apt 删除了这个版本。然后在haskell-platform主面，找到8.01的linux版本，但只是genic的64位完全版本（因为直接选择ubuntu 时，只能下载7.x的版本，所以是手工下载的通用linux的版本，haskell-platform-8.0.1-unknown-posix--full-x86_64.tar.gz）
在出现cabal update挂起的问题后，经过issues的帮助，已经解决。但接下来的步骤，还是有问题。

git clone https://github.com/winterland1989/magic-haskell.git
cd ./magic-haskell/code
cabal sandbox init
cabal install --only-dependencies
出现如下信息，没有成功。
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: primitive (dependency of conduit-extra-1.1.15)
rejecting: primitive-0.6.1.0/installed-Ip4... (conflict: primitive =>
transformers==0.5.2.0/installed-0.5..., code => transformers>=0.4 && <0.5)
trying: primitive-0.6.2.0
trying: scientific-0.3.4.6/installed-9fC... (dependency of
attoparsec-0.13.1.0)
next goal: vector (dependency of scientific-0.3.4.6/installed-9fC...)
rejecting: vector-0.11.0.0/installed-6uB... (conflict: primitive==0.6.2.0,
vector => primitive==0.6.1.0/installed-Ip4...)
rejecting: vector-0.11.0.0, vector-0.10.12.3, vector-0.10.12.2,
vector-0.10.12.1, vector-0.10.11.0, vector-0.10.10.0, vector-0.10.9.2,
vector-0.10.9.1, vector-0.10.9.0, vector-0.10.0.1, vector-0.10, vector-0.9.1,
vector-0.9, vector-0.8, vector-0.7.1, vector-0.7.0.1, vector-0.7,
vector-0.6.0.2, vector-0.6.0.1, vector-0.6, vector-0.5, vector-0.4.2,
vector-0.4.1, vector-0.4, vector-0.3.1, vector-0.3, vector-0.2, vector-0.1,
vector-0.10.12.0, vector-0.10.9.3 (conflict: scientific =>
vector==0.11.0.0/installed-6uB...)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

**Comment by boboyada** [comment]
当然，如果想恢复到ubuntu 的7.x的最新版本，则必须删除手工安装的haskell-platform 8.01(haskell-platform-8.0.1-unknown-posix--full-x86_64.tar.gz)，如何删除这个手工版本？）
再用 apt进行安装。

**Comment by winterland1989** [comment]
你试着把`transformers>=0.4 && <0.5`调整为`transformers>=0.4`呢？我不是很了解haskell-platform的版本体系，但是ubuntu的话推荐使用[hvr的ppa](https://launchpad.net/~hvr/+archive/ubuntu/ghc)。

**Comment by boboyada** [comment]
我卸载了8.01,然后使用了hvr的ppa安装了haskell-platform 7.10.3,问题同样。

我在win10环境下载了haskell-platform8.01,
C:\Users\yangboant\magic-haskell\code>cabal sandbox init
Writing a default package environment file to
C:\Users\yangboant\magic-haskell\code\cabal.sandbox.config
Creating a new sandbox at C:\Users\yangboant\magic-haskell\code\.cabal-sandbox

C:\Users\yangboant\magic-haskell\code>cabal install --only-dependencies
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: code-0.1.0.0 (user goal)
next goal: MonadRandom (dependency of code-0.1.0.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

**Comment by boboyada** [comment]
kylin ubuntu linux 16.10  
win10
两个OS环境，都这样

**Comment by winterland1989** [comment]
抱歉这个真的只是cabal的使用问题，你的问题报错信息都说的很清楚了（比如上面的信息告诉你请运行`cabal update`...），我们邮箱交流吧，谢谢。
