### ISSUE TITLE
p111-p114   结合律 组合律前后说法是否有不统一

### ISSUE THREAD

**Issue by boboyada** [winterland1989/magic-haskell#21]
p111，范畴三要素和两个公理(针对态射，即函数来说的)，
结合律公理(也是分配律吧?)，f.(g.h)=(f.g).h
单位律公理，id函数
p114第九行，fmap  (odd.sqrt)=(fmap odd).(fmap sqrt)，说这是函子在范畴学上的第二个约束，可p111好像没提到组合律。而提的是分配律。
这二个约束好像不是一回事?

**Comment by winterland1989** [comment]
是的，应该统一成结合律。是一回事。

**Comment by SamZhangQingChuan** [comment]
@winterland1989 ……
f(gh) = (fg)h 是结合律（associative）
f(a+b) = f(a)+f(b)是分配律 (distributive)
这两个完全不一样的……

对于态射适用的是结合律
对于functor适用的是分配律
FYI: 应该是木有组合律这种东西的……

**Comment by winterland1989** [comment]
貌似我没有用到分配律哇。你提到的两个地方都是结合律。不是么？

**Comment by SamZhangQingChuan** [comment]
@winterland1989 (fmap odd).(fmap sqrt) = fmap(odd.sqrt)这个东西就是分配律、、、

**Comment by winterland1989** [comment]
确实是这样 是个不小的错误 多谢指正！
