### ISSUE TITLE
p113  Haskell范畴

### ISSUE THREAD

**Issue by boboyada** [winterland1989/magic-haskell#22]
p113  有说巨大的Haskell范畴，在haskell范畴体系中，还有很多小范畴，能否请您结合maybe，[]两个函子，在haskell大范畴体系中，分别映射的范畴C和范畴D各是什么?
     当然这里先不论单子

**Comment by winterland1989** [comment]
抱歉元旦休假没看issue。对于`Maybe`来说，范畴C就是包含`Int, Bool, String...`这类物体的一个范畴，范畴D就是包含`Maybe Int, Maybe Bool, Maybe String...`的范畴。对于`[]`类似，这些范畴包含的关系就是类型之间的函数。
