### ISSUE TITLE
P142     monoid  (a->b)

### ISSUE THREAD

**Issue by boboyada** [winterland1989/magic-haskell#33]
魔力haskell一书第p142页
instance  Monoid  b  => Monoid(a->b)  where

      mempty  _   =  mempty     
--    1问   这里前后两个mempty各指谁?不会是同一个吧?

--   2问  这里针对 (a->b) 元素对应的mempty是多少，没有给出来，是id吗?

      mappend  f g  x  =  f x 'mappend'   g  x
这里比较好理解

**Comment by winterland1989** [comment]
1. 不是同一个，左侧的是待定义的`a -> b`的，右侧是`b`的。
2. 见上句。

**Comment by boboyada** [comment]
上句讲的是  a-->a  这种情况呀
instance Monoid  a => Monoid (a -> a) where
mempty = id
mappend =  。

f1：：a ->a
f2：：a->a
f1  `mappend`  f2   =  f1  。 f2

这与同一页的Endo雷同

**Comment by boboyada** [comment]
instance Monoid b => Monoid(a->b) where
      mempty = id                       ----是这样吗？
      mempty   _  = mempty         ----这一行有例子吗？下划线"__"是笔误吗？
      mappend f g x = f x  `mappend` g x

**Comment by winterland1989** [comment]
没有笔误，请参考前面的章节学习下`_`在模式匹配中的含义。此处`mempty`显然不等于`id`。

**Comment by boboyada** [comment]
mempty _ ，在这里下划线模式匹配，代表可以忽略的任何参数（另一个函数参数），代表mempty与任何参数相应用，最后得到b类型的mempty。
只是因为这个例子中，没有像其它的Monoid实例中，给出了具体的mempty的定义。比如列表的mempty=[]
所以，我才感觉到困惑

**Comment by winterland1989** [comment]
Yes！看来你已经get到了😅 基本上遇到`mempty`这类的多态值先看类型。

**Comment by boboyada** [comment]
？呵呵
instance Monoid b => Monoid(a->b) where
中 只有mempty  _ = memepty，
而没有mempty = ?
这里无法给出mempty = ??吗？ ，能再更详细点吗？我是不是太轴了：））

**Comment by winterland1989** [comment]
你确实是很轴啊哈哈哈😂

这里是定义`a -> b`的实例，所以被定义的`mempty`是一个函数，如果你非要一个所谓"直接"的定义，这样怎么样？

```haskell
instance Monoid (a ->b) where
    mempty = \ _ -> mempty
    …
```

**Comment by boboyada** [comment]
唉呀呀，我是函数式编程方面基础太差，概念和动手都贫乏，才如此轴。
谢谢你，喝完喜酒回来，看到这个实现，算是明白了，又过了个小坎坎
