### ISSUE TITLE
关于视频上传

### ISSUE THREAD

**Issue by hurui200320** [winterland1989/magic-haskell#37]
能不能不用爱奇艺。我在看第一个视频的时候，刚开头那里看不清命令行里再打cabal啥啥啥的，想下载下来然后放大看。但是爱奇艺这没法解析啊，他换算法了啊。所以能不能给个下载版，或者传到一个好解析下载地址的视频网站上，或者用录屏的方式把电脑上的操作录下来，这样能清楚一点。主要是我已经把分辨率调成1080了但还是看不清这第一个视频刚开头用的cabal命令是啥。。

**Comment by winterland1989** [comment]
主要是爱奇艺支持大文件（>1.5G）的上传，国内目前没找到其他的替代，有所不便实在抱歉哈。之后的视频应该以短视频录屏为主，多谢建议！

**Comment by hurui200320** [comment]
那可不可以放出视频的原档以供下载呢。因为每次用爱奇艺看都要等广告，而个人平时几乎不用爱奇艺，所以没开会员。但是使用爱奇艺客户端下载到的视频没办法用其他播放器解码，也不能放大看画面的细节，有些别扭呢。

**Comment by winterland1989** [comment]
这个当然是可以的 不过因为大小的缘故上传了几次百度网盘都中断了 有时间我再试试别的网盘吧

**Comment by hurui200320** [comment]
![image](https://cloud.githubusercontent.com/assets/8587572/22917648/5dadf94c-f2c9-11e6-808a-971c88d12ee3.png)
恩。。解决了。。就是第一集投影看不清楚，截图放进PS里调低亮度增大对比度就好了。

**Comment by winterland1989** [comment]
👍👍👍
