### ISSUE TITLE
[Errata] Chapter 05 Page 43

### ISSUE THREAD

**Issue by tisonkun** [winterland1989/magic-haskell#50]
第 43 页最下方的代码示例 `giveMeFive $ zip [0..] [100..1]` 应该为 `giveMeFive $ zip [0..] [100..1]`, 同样还有 44 页的后续相关代码.

**Comment by winterland1989** [comment]
应该把 `[100..1]` 改成 `[100,99..1]` ，多谢！

**Comment by tisonkun** [comment]
@winterland1989 如果以其他形式记录的话，可以把这个 issue 关了（x

**Comment by winterland1989** [comment]
暂时保留在这，第二版修订的时候再来关 XD

**Comment by tisonkun** [comment]
Closed as no more activities.
